server:
  port: 12332

logging:
  level:
    root: info

spring:
  application:
    name: tcc-transaction-server
  cloud:
    #默认不使用注册中心
    #使用nacos为注册中心
    nacos:
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
    #使用zookeeper为注册中心
    zookeeper:
      enabled: false
      connect-string: localhost:2181
  tcc:
#    request-process-thread-queue-capacity: 1024
    storage:
#      kryo-pool-size: 512
      storage-type: memory
      max-attempts: 1
#      jdbc:
#        password: welcome1
#      redis:
#        host: 127.0.0.1
#        port: 6379
#        database: 0
#        pool-config:
#          max-total: 100
#          max-idle: 100
#          min-idle: 10
#          max-wait-millis: 300
#      redis-cluster:
#        max-attempts: 5
#        so-timeout: 300
#        connection-timeout: 1000
#        nodes:
#          - host: 127.0.0.1
#            port: 6379
#          - host: 127.0.0.1
#            port: 6380
#          - host: 127.0.0.1
#            port: 6381
#      shard-redis:
#        nodes:
#          - host: 127.0.0.1
#            port: 6379
#          - host: 127.0.0.1
#            port: 6380
#          - host: 127.0.0.1
#            port: 6381
    recovery:
#      recovery-enabled: true
#      update-job-forcibly: false
      quartz-clustered: true
#      quartz-data-source-url: jdbc:mysql://localhost:3306/TCC_SERVER?useSSL=false&allowPublicKeyRetrieval=true
#      quartz-data-source-driver: com.mysql.jdbc.Driver
#      quartz-data-source-user: root
#      quartz-data-source-password: welcome1
    registry:
      registry-address: 127.0.0.1:2332
#      registry-type: direct
#      cluster-name: default
#      zookeeper:
#        connect-string: 127.0.0.1:2181
#        max-retries: 4
#      nacos:
#        server-addr: 127.0.0.1:8848
#    remoting:
#      listen-port: 2332
