server:
  port: 9998

logging:
  level:
    root: info

spring:
  application:
    name: tcc-transaction-server
  tcc:
    request-process-thread-queue-capacity: 1024
    storage:
      kryo-pool-size: 512
      storage-type: redis
      max-attempts: 1
      redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        pool-config:
          max-total: 100
          max-idle: 100
          min-idle: 10
          max-wait-millis: 300
      redis-cluster:
        max-attempts: 5
        so-timeout: 300
        connection-timeout: 1000
        nodes:
          - host: 127.0.0.1
            port: 6379
          - host: 127.0.0.1
            port: 6380
          - host: 127.0.0.1
            port: 6381
      shard-redis:
        nodes:
          - host: 127.0.0.1
            port: 6379
          - host: 127.0.0.1
            port: 6380
          - host: 127.0.0.1
            port: 6381
    recovery:
      recovery-enabled: true
      update-job-forcibly: true
      quartz-data-source-password: 123456
      quartz-clustered: true
      cron-expression: "0/10 * * * * ? "
    registry:
      registry-address: 127.0.0.1:2332
      registry-type: nacos
      cluster-name: default
      zookeeper:
        connect-string: 127.0.0.1:2181
        max-retries: 4
      nacos:
        server-addr: 127.0.0.1:8848
    remoting:
      listen-port: 2332